version: '3'
services:
  pat:
    image: docker.io/la5nta/pat:latest
    user: 1000:1000
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "./data/pat:/app/pat"
    environment:
      - "PAT_ARDOP_ADDR=ardop:8515"
      - "PAT_AGWPE_ADDR=direwolf:8000"
      - "PAT_VARAHF_ADDR=varahf:8300"
      - "PAT_VARAFM_ADDR=varafm:8300"
      - "PAT_HAMLIB_RIGS_dummy=rigctld-dummy:4532"
  ardop:
    image: ardopcf
    build: ./.services/ardopcf
    environment:
      - DEVNAME=plughw:1,0,1
    devices:
      - /dev/snd
  direwolf:
    image: direwolf
    build: ./.services/direwolf
    environment:
      - DEVNAME=plughw:1,0,1
    devices:
      - /dev/snd
  rigctld-dummy:
    image: hamlib
    build: ./.services/hamlib
    command: -m 1
  varafm:
    image: vara
    build: ./.services/vara
    environment:
      - CARD=1
      - DEVICE=0
      - SUBDEVICE=0
    devices:
      - /dev/snd
    entrypoint: varafm
  varahf:
    image: vara
    build: ./.services/vara
    environment:
      - CARD=1
      - DEVICE=0
      - SUBDEVICE=0
    devices:
      - /dev/snd
    entrypoint: varahf
